config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  get'/login' => 'pages#login'
  get'/signup' => 'pages#signup'

  get '/customer_login' => 'customer_session#new'
  post '/customer_login' => 'customer_session#create'
  delete 'customer_login' => 'customer_session#destroy'

  get '/driver_login' => 'driver_session#new'
  post '/driver_login' => 'driver_session#create'
  delete 'driver_login' => 'driver_session#destroy'

  resources :customers
  resources :drivers
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :customer, :optional =>true
    belongs_to :driver, :optional =>true

    geocoded_by :from_address
    after_validation :geocode
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :bookings
    has_secure_password
    validates :email, :presence => true, :uniqueness => true

    # geocoded_by :address
    # after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

    # def address
    #     [street,]
    # end
end

app/models/driver.rb
class Driver < ApplicationRecord
    has_many :bookings
    has_secure_password
    validates :email, :presence => true, :uniqueness => true
end

app/models/user.rb
class User < ApplicationRecord
    geocoded_by :ip_address,
    :latitude => :lat, :longitude => :lon
    after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_customer
    before_action :fetch_driver

    private
    def fetch_customer
        @current_customer = Customer.find_by :id => session[:customer_id] if session[:customer_id].present?
        session[:customer_id] = nil unless @current_customer.present? # Log out non-existant customers
    end

    def fetch_driver
        @current_driver = Driver.find_by :id => session[:driver_id] if session[:driver_id].present?
        session[:driver_id] = nil unless @current_driver.present? # Log out non-existant drivers
    end

    def check_for_customer_login
        redirect_to customer_login_path unless @current_customer.present?
    end

    def check_for_driver_login
        redirect_to driver_login_path unless @current_driver.present?
    end

    def check_for_customer_login_booking (booking)
        redirect_to customer_login_path unless (@current_customer.present? && @current_customer.id == booking.customer_id)
    end

    def check_for_driver_login_booking (booking)
        redirect_to driver_login_path unless (@current_driver.present? && @current_driver.id == booking.driver_id)
    end

    def check_for_admin
        redirect_to root_path unless (@current_customer.present? && @current_customer.admin?)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :check_for_customer_login, :only => [:new, :create,:show,:edit, :update, :destroy]
  # before_action :check_for_driver_login, :only => [:index,:show,:edit, :update]
  # Only customer could create new booking and cancel(delete, because we don't want unconfirmed booking in the db) booking. Only driver could view booking index. Only logged in users could view history booking(his own bookings) and change booking status.


  def index
    @bookings = Booking.all
  end
  
  def new
    @booking = Booking.new
    # check_for_customer_login_booking @booking
  end

  def create
    booking = Booking.create booking_params 
    @current_customer.bookings << booking
    redirect_to booking
  end

  def show
    @booking = Booking.find params[:id]
    # check_for_driver_login_booking(@booking)

    # using gon and geocoder to pass coordinates from rails to google map api, which is written in JavaScript
    gon.from_address_lat=Geocoder.coordinates("#{@booking.from_address}")[0]
    gon.from_address_lon=Geocoder.coordinates("#{@booking.from_address}")[1]
    gon.to_address_lat=Geocoder.coordinates("#{@booking.to_address}")[0]
    gon.to_address_lon=Geocoder.coordinates("#{@booking.to_address}")[1]

  end

  def edit
    @booking = Booking.find params[:id]
  end

  def update
    booking = Booking.find params[:id]
    booking.update booking_params
    redirect_to booking
  end

  def destroy
    booking = Booking.find params[:id]
    booking.destroy
    redirect_to new_booking_path
  end

  private
  def booking_params
    params.require(:booking).permit(:estimated_price, :customer_id, :driver_id, :from_address, :to_address)
  end
end

app/controllers/customer_session_controller.rb
class CustomerSessionController < ApplicationController
    def new
    end
  
    def create
      customer = Customer.find_by :email => params[:email]
      if customer.present? && customer.authenticate(params[:password])
        session[:customer_id] = customer.id
        redirect_to new_booking_path
      else
        flash[:error_message] = "Invalid email or password"
        redirect_to customer_login_path
      end
    end
  
    def destroy
      session[:customer_id] = nil
      redirect_to customer_login_path
    end
  
  end
  

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :check_for_customer_login, :except => [:new, :create]
  # before_action :check_for_admin, :only => [:index]

  # def index
  #   @customers = Customer.all
  # end
  # not allowed to see customer index for now, new feature to be added in the future

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new customer_params
    if @customer.save
      session[:customer_id] = @customer.id
      redirect_to new_booking_path
    else
      render :new
    end
  end

  def show
    @customer = Customer.find params[:id]
  end

  def edit
    @customer = Customer.find params[:id]
  end

  def update
    customer = Customer.find params[:id]
    customer.update customer_params
    redirect_to customer
  end

  def destroy
    customer = Customer.find params[:id]
    customer.destroy
    redirect_to customers_path
end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :street, :suburb, :postcode, :state, :email, :password, :password_confirmation, :phone, :credit_card_no, :credit_card_expiry_date, :cvv)
  end
end

app/controllers/driver_session_controller.rb
class DriverSessionController < ApplicationController
    def new
    end

    def create
        driver = Driver.find_by :email => params[:email]
        if driver.present? && driver.authenticate(params[:password])
            session[:driver_id] = driver.id
            redirect_to bookings_path
        else
            flash[:error_message] = "Invalid email or password"
            redirect_to driver_login_path
        end
    end

    def destroy
        session[:driver_id] = nil
        redirect_to driver_login_path
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :check_for_driver_login, :except => [:new, :create]
  # before_action :check_for_admin, :only => [:index]

  # def index
  #   @drivers = Driver.all
  # end
  # not allowed to see driver index for now, new feature to be added in the future

  def new
    @driver = Driver.new
  end

  def create
    @driver = Driver.new driver_params
    if @driver.save
      session[:driver_id] = @driver.id
      redirect_to bookings_path
    else
      render :new
    end
  end

  def show
    @driver = Driver.find params[:id]
  end

  def edit
    @driver = Driver.find params[:id]
  end

  def update
    driver = Driver.find params[:id]
    driver.update driver_params
    redirect_to driver
  end

  def destroy
    driver = Driver.find params[:id]
    driver.destroy
    redirect_to drivers_path
end

  private
  def driver_params
    params.require(:driver).permit(:first_name, :last_name, :street, :suburb, :postcode, :state, :email, :password, :password_confirmation, :phone, :bank_bsb_no, :bank_account_no, :car_model_id, :driver_license_no)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/bookings/index.html.erb
<div id="bookings-index" class="row">
  <div class="col-md-6 offset-md-3">
    <h4>Available Jobs List</h4>
    <% @bookings.each do |booking| %>
      <% if booking.status=="new" %>
        <div class="row booking-index-container">
          <div class="col-md-8 booking-index-left">
            <p>Created at: <%= booking.created_at %></p>
            <p>From: <%= booking.from_address %></p>
            <p>To: <%= booking.to_address %></p>
          </div>

          <div class="col-md-4 booking-index-right">
            <button class="btn btn-primary">Take job</button>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div id="booking-new" class="row">
    <div class="col-md-8 offset-md-2">
        <h1>New booking</h1>

        <%= form_for @booking do |f| %>

            <div class="form-group">
                <%= f.label :from_address %>
                <%= f.text_field :from_address, :class => 'form-control'  %>
            </div>

            <div class="form-group">
                <%= f.label :to_address %>
                <%= f.text_field :to_address, :class => 'form-control' %>
            </div>

            <%= f.submit "Create booking", :class => 'btn btn-success btn-lg' %>

        <% end %>
    </div>
</div>

app/views/bookings/show.html.erb
<% # google direction api code start %>
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script>

  function initMap() {
    const directionsRenderer = new google.maps.DirectionsRenderer();
    const directionsService = new google.maps.DirectionsService();
    const map = new google.maps.Map(document.getElementById("map"), {
      zoom: 14,
    //   center: { lat: 37.77, lng: -122.447 },
    });
    directionsRenderer.setMap(map);
    calculateAndDisplayRoute(directionsService, directionsRenderer);
    document.getElementById("mode").addEventListener("change", () => {
      calculateAndDisplayRoute(directionsService, directionsRenderer);
    });
  }

  function calculateAndDisplayRoute(directionsService, directionsRenderer) {
    const selectedMode = document.getElementById("mode").value;
    console.log(gon.from_address_lat)
    console.log(gon.from_address_lon)
    console.log(gon.to_address_lat)
    console.log(gon.to_address_lon)
    directionsService.route(
      {
        origin: { lat: gon.from_address_lat, lng: gon.from_address_lon },
        destination: { lat: gon.to_address_lat, lng: gon.to_address_lon },
        // Note that Javascript allows us to access the constant
        // using square brackets and a string value as its
        // "property."
        travelMode: google.maps.TravelMode[selectedMode],
      },
      (response, status) => {
        if (status == "OK") {
          directionsRenderer.setDirections(response);
        } else {
          window.alert("Directions request failed due to " + status);
        }
      }
    );
  }
</script>
<% # google direction api code end %>

<% # geocoder to calculate coordinates, distance and estimated price start %>
<% 
  # remove condition later because no need
  if @current_customer.nil?
    current_booking = Booking.find params[:id]
  else
    current_booking = Booking.find params[:id]
  end

  from_coordinates = Geocoder.coordinates("#{current_booking.from_address}")

  to_coordinates = Geocoder.coordinates("#{current_booking.to_address}")

  distance = (Geocoder::Calculations.distance_between([from_coordinates[0],from_coordinates[1]], [to_coordinates[0],to_coordinates[1]])*1.60934 *1.15).round(2)
  #1.60934 is to transfer mile into km; 1.15 is estimated transfer from straight distance between coordinates to actual routes distance

  estimated_price = (distance * 2.7).round(2)
  # 2.7 is estimated transfer from distance to price
  @booking.estimated_price = estimated_price
  @booking.save
%>
<% # geocoder to calculate coordinates, distance and estimated price end %>

<div id="booking-show-offset1" class="row">
  <div class="col-md-12"></div>
</div>

<div id="booking-show-main" class="row">
  <div class="col-md-4 offset-md-1">
    <ul>
      <li>From: <%= @booking.from_address %></li>
      <li>To: <%= @booking.to_address %></li>
      <li>Distance: <%= distance %> km</li>
      <li>Estimated price: $<%= estimated_price %></li>
      <% if @booking.driver.present? %>
      <li>Driver: <%=link_to @booking.driver.email, @booking.driver %></li>
      <% end %>
    </ul>

    <% if @booking.status=="new" %>
      <div class="controls">  
        <div class="row">
          <div class="col-md-6">
            <%= button_to 'Cancel booking', @booking, :method => 'delete', :data => {:confirm => 'Are you sure?' }, class: "button btn-danger"%>
          </div>

          <div class="col-md-6">
              <%= form_for @booking do |t|%>
              <%= t.hidden_field :status, @booking.status=> "confirmed" %>
              <%= t.submit "Confirm booking", class: "button btn-success", :id=>"confirm-booking" %>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-7">
    <div id="floating-panel">
      <b>Mode of Travel: </b>
      <select id="mode">
        <option value="DRIVING">Driving</option>
        <option value="WALKING">Walking</option>
        <option value="BICYCLING">Bicycling</option>
        <option value="TRANSIT">Transit</option>
      </select>
    </div>
    <div id="map"></div>
  </div>
</div>

<%# <div id="waiting_for_driver">
  <p>Waiting for driver to take the job...</p>
</div> %>

<% # google direction api code start %>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjI23uIXRb73MjkDTGcrkN_OJy7i0dbS0&callback=initMap"></script>
<% # google direction api code end %>

app/views/customer_session/new.html.erb
<div class="row">
  <div id="sign-in-offset1"  class="col-md-12">
  </div>
</div>

<div id="customer-sign-in-main" class="row">
  <div class="col-md-8 offset-md-2">
    <h5>Sign in to ride</h5>
    <% if flash[:error_message] %>
      <h2><%= flash[:error_message] %></h2>
    <% end %>

    <%= form_tag customer_login_path do  %>
      <div class="row">
        <div class="col-md-12">
          <%= email_field_tag :email, nil, :placeholder=>'Email' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= password_field_tag :password, nil, :placeholder=>'Password' %>
        </div>
      </div>

    <%= submit_tag "Sign in", :class => 'btn btn-success'  %>

    <% end %>
  </div>
</div>

app/views/customers/edit.html.erb
<div id="driver-sign-up-offset1"  class="row"></div>

<div class="row">
    <div id="driver-sign-up-header" class="col-md-6 offset-md-1">
        <h3>Go anywhere with Ubor!</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet iste maxime, necessitatibus sapiente ex ipsa. Excepturi ad animi sed rerum. Adipisci vitae consequuntur nesciunt porro voluptates exercitationem, minus architecto temporibus.</p>
    </div>  
</div>

<div class="row">
    <div id="driver-sign-up-bg" class="col-md-12">
        <img src="/assets/driver_sign_up_hero_banner.png" alt="">
    </div>
</div>

<div class="sign_up_form">
    <% if @customer.errors.any? %>
        <ol>
            <% @customer.errors.full_messages.each do|msg| %>
                <li><%= msg %></li>
            <% end %>
        </ol>
    <% end %>

    <div class="form-containter ">
        <%= form_for @customer do |f|%>
        <h6>Edit profile</h6>

        <div class="row">
            <div class="col-md-6">
                <%= f.email_field :email, :placeholder=>"Email", :required=>true %>
            </div>

            <div class="col-md-6">
                <%= f.text_field :phone, :placeholder=>"Phone"  %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.password_field :password, :placeholder=>"Password" %> 
            </div>

            <div class="col-md-6">
                <%= f.password_field :password_confirmation, :placeholder=>"Password confirmation" %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :first_name, :required => true, :placeholder=>"First name" %>
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :last_name, :required => true, :placeholder=>"Last name" %> 
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :street, :placeholder=>"Street" %> 
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :suburb, :placeholder=>"Suburb" %> 
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :state, :placeholder=>"State" %> 
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :postcode, :placeholder=>"Postcode" %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :credit_card_no, :placeholder=>"Credit card" %>
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :credit_card_expiry_date, :placeholder => 'Expiry date'%> 
            </div>
        </div>       

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :cvv, :placeholder=>"cvv" %>
            </div>
        </div>   

       <div class="row">
           <div class="col-md-12">
            <%= f.submit "Edit profile", :class => 'btn btn-success'%>
           </div>
       </div>
        
       <% end %>
    </div>  

</div>

app/views/customers/index.html.erb
<h1>All Customers</h1>

<% @customers.each do |customer| %>
  <p><%= customer.email %></p>
<% end %>

app/views/customers/new.html.erb
<div id="driver-sign-up-offset1"  class="row"></div>

<div class="row">
    <div id="driver-sign-up-header" class="col-md-6 offset-md-1">
        <h3>Go anywhere with Ubor!</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Amet iste maxime, necessitatibus sapiente ex ipsa. Excepturi ad animi sed rerum. Adipisci vitae consequuntur nesciunt porro voluptates exercitationem, minus architecto temporibus.</p>
    </div>  
</div>

<div class="row">
    <div id="driver-sign-up-bg" class="col-md-12">
        <img src="/assets/driver_sign_up_hero_banner.png" alt="">
    </div>
</div>

<div class="sign_up_form">
    <% if @customer.errors.any? %>
        <ol>
            <% @customer.errors.full_messages.each do|msg| %>
                <li><%= msg %></li>
            <% end %>
        </ol>
    <% end %>

    <div class="form-containter ">
        <%= form_for @customer do |f|%>
        <h6>Sign up now</h6>


        <div class="row">
            <div class="col-md-6">
                <%= f.email_field :email, :placeholder=>"Email", :required=>true %>
            </div>

            <div class="col-md-6">
                <%= f.text_field :phone, :placeholder=>"Phone"  %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.password_field :password, :placeholder=>"Password" %> 
            </div>

            <div class="col-md-6">
                <%= f.password_field :password_confirmation, :placeholder=>"Password confirmation" %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :first_name, :required => true, :placeholder=>"First name" %>
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :last_name, :required => true, :placeholder=>"Last name" %> 
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :street, :placeholder=>"Street" %> 
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :suburb, :placeholder=>"Suburb" %> 
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :state, :placeholder=>"State" %> 
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :postcode, :placeholder=>"Postcode" %>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :credit_card_no, :placeholder=>"Credit card" %>
            </div>
            
            <div class="col-md-6">
                <%= f.text_field :credit_card_expiry_date, :placeholder => 'Expiry date'%> 
            </div>
        </div>       

        <div class="row">
            <div class="col-md-6">
                <%= f.text_field :cvv, :placeholder=>"cvv" %>
            </div>
        </div>   

       <div class="row">
           <div class="col-md-12">
            <%= f.submit "Sign up!", :class => 'btn btn-success'%>
           </div>
       </div>
        
       <% end %>
    </div>
</div>

app/views/customers/show.html.erb
<div id="customers-show-main" class="row">
    <div class="col-md-8 offset-md-2">
        <h5>
            Welcome, <%= @customer.first_name + " " + @customer.last_name %>
        </h5>

        <h6>Profile:</h6>

        <ul>
            <li>Email: <%= @customer.email %></li>
            <li>Phone: <%= @customer.phone %></li>
            <li>Street: <%= @customer.street %></li>
            <li>Suburb: <%= @customer.suburb %></li>
            <li>Postcode: <%= @customer.postcode %></li>
            <li>State: <%= @customer.state %></li>
            <li>Credit card: <%= @customer.credit_card_no %></li>
            <li>Expirty date: <%= @customer.credit_card_expiry_date %></li>
            <li>cvv: <%= @customer.cvv %></li>
        </ul>
   
        <div class="control">
            <div class="row">
                <div class="col-md-3 offset-md-3">
                    <%= button_to 'Edit profile', edit_customer_path(@customer),class:"button btn-success",:method => "get" %>
                </div>
                
                <div class="col-md-3">
                    <%= button_to 'Delete account', @customer, :method => :delete, :data => {:confirm => 'Are you sure?'},class:"button btn-danger" %>             
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <h6>History bookings</h6>
                <ol>
                    <% @customer.bookings.each do |booking| %>
                        <li>Created time: <%= link_to booking.created_at.to_s, booking %></li>
                    <% end %>
                </ol>
            </div>
        </div>
    </div>
</div>
   

app/views/driver_session/new.html.erb
<div class="row">
  <div id="sign-in-offset1"  class="col-md-12">
  </div>
</div>

<div id="driver-sign-in-main" class="row">
  <div class="col-md-8 offset-md-2">
    <h5>Sign in to drive</h5>
    <% if flash[:error_message] %>
      <h2><%= flash[:error_message] %></h2>
    <% end %>

    <%= form_tag driver_login_path do  %>
      <div class="row">
        <div class="col-md-12">
          <%= email_field_tag :email, nil, :placeholder=>'Email' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= password_field_tag :password, nil, :placeholder=>'Password' %>
        </div>
      </div>

    <%= submit_tag "Sign in", :class => 'btn btn-success'  %>

    <% end %>
  </div>
</div>

app/views/drivers/index.html.erb
<h1>All Drivers</h1>

<% @drivers.each do |driver| %>
  <p><%= driver.email %></p>
<% end %>

app/views/drivers/show.html.erb
<div id="customers-show-main" class="row">
    <div class="col-md-8 offset-md-2">
        <h5>
            Welcome, <%= @driver.first_name + " " + @driver.last_name %>
        </h5>

        <h6>Profile:</h6>

        <ul>
            <li>Email: <%= @driver.email %></li>
            <li>Phone: <%= @driver.phone %></li>
            <li>Street: <%= @driver.street %></li>
            <li>Suburb: <%= @driver.suburb %></li>
            <li>Postcode: <%= @driver.postcode %></li>
            <li>State: <%= @driver.state %></li>
            <li>Credit card: <%= @driver.bank_bsb_no %></li>
            <li>Expirty date: <%= @driver.bank_account_no %></li>
            <li>cvv: <%= @driver.driver_license_no %></li>
        </ul>
   
        <div class="control">
            <div class="row">
                <div class="col-md-3 offset-md-3">
                    <%= button_to 'Edit profile', edit_driver_path(@driver),class:"button btn-success",:method => "get" %>
                </div>
                
                <div class="col-md-3">
                    <%= button_to 'Delete account', @driver, :method => :delete, :data => {:confirm => 'Are you sure?'},class:"button btn-danger" %>             
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <h6>History bookings</h6>
                <ol>
                    <% @driver.bookings.each do |booking| %>
                        <li>Created time: <%= link_to booking.created_at.to_s, booking %></li>
                    <% end %>
                </ol>
            </div>
        </div>
    </div>
</div>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ubor</title>
    
    <%= csrf_meta_tags %>

    <%= Gon::Base.render_data %>

    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= params[:controller] %> <%= params[:action] %>">
    <div class="row">
      <div class="col-md-4 nav-line"  id="nav-left">
        <a href='/'>Ubor</a>
      </div>
      <div class="col-md-8  nav-line">
        <nav>
          <% if @current_customer.present? %>
            <%= link_to "Customers", customers_path if @current_customer.admin? %>   
            <%= link_to "New booking |", new_booking_path %>     
            <%= link_to "Customer profile |", @current_customer %>  
            <%= link_to "Logout", customer_login_path, :method => 'delete' %>
          <% elsif @current_driver.present? %>
            <%= link_to "Jobs |", bookings_path %>
            <%= link_to "Driver profile |", @current_driver %> 
            <%= link_to "Logout", driver_login_path, :method => 'delete' %>
          <% else %>
            <%= link_to "log in |", login_path, :id=>"log_in" %>
            <%= link_to "sign up", signup_path, :id=>"sign_up"  %>
          <% end %>
        </nav>
      </div>
    </div>
    
    <div class="row">
      <div class="container col-md-12">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div id='offset1' class="row"></div>

<div class="row">
    <div id="entrance" class="col-md-4 offset-md-2">
        <div id="entrance-header" class="row">
            <div id="entrance-header-left" class="col-md-6">
                <img src="/assets/drive_icon.svg" alt="">
                <p>Drive</p>
            </div>
            <div id="entrance-header-right" class="col-md-6">
                <img src="/assets/ride_icon.svg" alt="">
                <p>Ride</p>
            </div>
        </div>

        <div id="entrance-main-1" class="row">
            <h2>Get in the driver's seat and get paid</h2>
            <p>Drive on the platform with the largest network of active riders.</p>
            <%= button_to "Sign up to drive", new_driver_path, :method=>"get", :class => "btn btn-primary" %>
        </div>

        <div id="entrance-main-2" class="row">
            <h2>Take a ride with us to explore</h2>
            <p>Explore the wrold with Ubor, we are always with you on the way.</p>
            <%= button_to "Sign up to ride", new_customer_path, :method=>"get", :class => "btn btn-success" %>
        </div>
    </div>
</div>

app/views/pages/login.html.erb
<div class="row">
    <div id="sign_in_drive" class="col-md-4 log_in">
        <h4><%= link_to "Sign in to drive", driver_login_path %></h4>
        <h4 class='arrow'>→</h4>
    </div>
    
    <div id="sign_in_ride" class="col-md-4 log_in">
        <h4><%= link_to "Sign in to ride", customer_login_path %></h4>
        <h4 class='arrow'>→</h4>
    </div>
</div>

app/views/pages/signup.html.erb
<div class="row">
    <div id="sign_in_drive" class="col-md-4 log_in">
        <h4><%= link_to "Signup to drive", new_driver_path %></h4>
        <h4 class='arrow'>→</h4>
    </div>
    
    <div id="sign_in_ride" class="col-md-4 log_in">
        <h4><%= link_to "Create a rider account", new_customer_path %></h4>
        <h4 class='arrow'>→</h4>
    </div>
</div>

app/views/session/new.html.erb
<h1>Log In</h1>

<% if flash[:error_message] %>
  <h2><%= flash[:error_message] %></h2>
<% end %>

<%= form_tag login_path do  %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag "Sign In" %>

<% end %>